name: 'codeartifact-setup'
description: 'AWS CodeArtifact Setup'
author: 'InteropIO'

# Define your inputs here.
inputs:
  domain:
    description: 'Domain'
    required: true
    default: 'interopio'
  domain-owner:
    description: 'Domain Owner'
    required: true
    default: '389653476181'
  region:
    description: 'Region'
    required: true
    default: 'eu-central-1'
  duration:
    description: 'Token expiration in seconds'
    required: false
    default: '18000'

outputs:
  token:
    description: 'Auth Token'

runs:
  using: node20
  main: dist/index.js
